### ISSUE TITLE
Hangup in socket.py

### ISSUE THREAD

**Issue by JoeStaines** [nhammond129/ch.py#67] opened 2015-06-07 17:58 UTC
Not sure if this is a specific issue for ch.py or if it's a wider issue, but the bot just started to hang up after a while and i had to interrupt it.

Trace:

```
Traceback (most recent call last):
  File "fvbot.py", line 220, in <module>
    FVBot.easy_start(["fv-se"], fvbotauth.FVBOT_USER, fvbotauth.FVBOT_PASS, True)
  File "C:\Users\Joe\Documents\GitHub\FVBot\ch.py", line 2182, in easy_start
    self.main()
  File "C:\Users\Joe\Documents\GitHub\FVBot\ch.py", line 2140, in main
    rd, wr, sp = select.select(socks, wsocks, [], self._TimerResolution)
  File "C:\Python27\lib\socket.py", line 223, in meth
    def meth(name,self,*args):
KeyboardInterrupt
```

**Comment by asl97** [comment] 2015-06-07 18:13
i blame chatango and maybe the stdlib

in any case,  this isn't a issue with the library

**Comment by LordYusei** [comment] 2015-08-26 07:28
Yo9u need python 3.3.3 at least to run the python bot. Lol

**Comment by asl97** [comment] 2015-08-26 13:18
@LordYusei the original ch.py support python 2 and python 3

the last time i check, this "updated" copy also support python 2 and python3 although someone could have added python 3 only features.

**Comment by LordYusei** [comment] 2015-08-26 13:20
Hmm, i only ever had luck with python3 with this. Maybe you're just lucky

**Comment by asl97** [comment] 2015-08-26 13:24
@LordYusei you should check the website before replying if possible cause when someone edit their post, github doesn't send any message about the edit.

in any case, this is where python2 compatibility is done: https://github.com/Nullspeaker/ch.py/blob/master/ch.py#L52

**Comment by LordYusei** [comment] 2015-08-26 13:26
So it does. I missed that when i was using it. Lol

**Comment by LordYusei** [comment] 2015-09-08 20:55
@JoeStaines If you wanted to make it so you were notified of an error you could do something like this for when the bot errors while running.
if __name__ == "__main__":
	error = 0
	try:
		os.system("clear") # Clears the python console so that if you have info it removes it and starts fresh
		TestBot.easy_start(rooms, "Username", "Password")
	except KeyboardInterrupt:
		print("[ERR] Console initiated a kill.")
	except Exception as e:
		print("[ERR] Fatal error.")
		error = 1
		hexc(e)

if error = 1:
      print("Waiting 5 seconds to disconnect the operations")
      time.sleep(5)
print("Shutting down")

**Comment by piks** [comment] 2015-09-09 13:00
so... is this an issue? XD

**Comment by LordYusei** [comment] 2015-09-09 13:20
@piks Honestly, No idea. In my use of ch.py all I had was errors thrown upon entering the bot in certain chats. It was mainly like chats with large amounts of users joining and leaving rapidly.

From what I can create similar to his issue, It seems to be caused by a function he has created. More than likely it's a function that either runs constantly when executed, or just runs from startup and glitches out the bot. I'm not sure it's something that needs to be looked into for that part but more something that he needs to check his code for.

**Comment by asl97** [comment] 2015-09-09 23:37
wrapping the whole bot in a `try except` just to capture the error and display it is a flaw method, it's one of the reason why the old botteh code give rubbish errors, just let it error normally.

to see the error without it closing as soon as it error, it should ether be started using the terminal/cmd or as a service with proper message piping.

@LordYusei format your code using markdown next time please,
also, hexc doesn't seem to be define.

**Comment by mor0n** [comment] 2015-09-20 14:06
How can I log as anon instead of user?

**Comment by asl97** [comment] 2015-09-21 05:28
@mor0n off-topic, this issue is about hangup in socket.py

**Comment by mor0n** [comment] 2015-09-21 06:29
@asl97 so where I can ask about it?

**Comment by asl97** [comment] 2015-09-22 21:29
@mor0n don't know, don't care. there was never an official support channel or anything.

at best, you would have to find someone who is not only knowledgeable about the library itself (and maybe the chatango protocol if something has change) but also willing to help you with it.

you could try opening an issue but it would still be off-topic if you title it "`How can I log as anon instead of user?`" since that would be an question and not a issue.

even if you make it sound more like an issue or even an feature request so it suit the issue tracker more but i doubt people who know about it would bother responding.
____
**the ch.py has long been abandon by the original author** and most if not all the current collaborators and contributions.

you should find another better maintain library than the ch.py, maybe one with a support channel (there are some information on others on the unofficial wikia).

**Comment by asl97** [comment] 2023-06-14 02:46
Closing due to old age, and no longer supporting python2

**Closed by asl97** 2023-06-14 02:46 UTC
Labels: info needed
